### ISSUE TITLE
how to add new container with properties using json-ld file 

### ISSUE THREAD

**Issue by andybuki** [fcrepo-exts/fcrepo-java-client#51]
I try to create a new container with properties using json-ld file. 
If i add json-ld file i always get 400 issue.
If file is empty, it creates an empty container without properties.

```
File file = new File("test.json");
try (FcrepoResponse response = new PostBuilder(uri, client).slug("test")
                .body(file, "text/turtle").filename("test")
                .perform();) {
            URI location = response.getLocation();
            System.out.println(response.getStatusCode());
```
           
Here small json-ld file
```
{
  "@context": "https://json-ld.org/contexts/person.jsonld",
  "@id": "http://dbpedia.org/resource/John_Lennon",
  "name": "John Lennon",
  "born": "1940-10-09"
}
```

If it's not possible to use json-ld, how should the other format look like?

**Comment by awoods** [comment]
Hello @andybuki ,
A couple of questions:
1. What version of Fedora are you using?
2. What (if any) error message are you getting in your Fedora log?

**Comment by andybuki** [comment]
Hi Andrew,

i took the last Fedora version 5.1.0
If i try to create a container with file (json-ld for example) i get following:
response.getStatusCode() --> 400
response.getLocation() --> null

**Comment by awoods** [comment]
Thanks!
Fedora 5.1.0 enforces a requirement that the subject of the RDF that you are posting to a Fedora resource match the URI of the Fedora resource itself. In your case, the subject of the RDF is:
> http://dbpedia.org/resource/John_Lennon
..which is not the same as the Fedora resource URI, which is:
> http://localhost:8080/fcrepo/rest/test
- Note: The host/port/context ("http://localhost:8080/fcrepo") may be different in your installation

If you change your json-ld file to look like the following, your request should work:
```
{
  "@context": "https://json-ld.org/contexts/person.jsonld",
  "@id": "http://localhost:8080/fcrepo/rest/test",
  "name": "John Lennon",
  "born": "1940-10-09"
}
```

Alternatively, you could change your json-ld to:
```
{
  "@context": "https://json-ld.org/contexts/person.jsonld",
  "@id": "http://localhost:8080/rest/John_Lennon",
  "name": "John Lennon",
  "born": "1940-10-09"
}
```
..and change your request to:
```
new PostBuilder(uri, client).slug("John_Lennon")
```

You may also want to change the Content-Type in the request to be "application-ld+json" instead of "text/turtle".

Finally, the upcoming Fedora 6.0 will not have the restriction noted above... so your request should work... although it currently does not, hence the new bug-tracking ticket: [FCREPO-3588](https://jira.lyrasis.org/browse/FCREPO-3588)
Posting your RDF as a Turtle file to Fedora 6 should work fine.
```
<> <http://xmlns.com/foaf/0.1/name> "John Lennon";
   <http://schema.org/birthDate> "1940-10-09";
```

**Comment by andybuki** [comment]
Thanks a lot now it works.
I corrected json-ld file and  renamed json-ld file, in my case, like John_Lennon.json

Best regards
Andrey
